[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kimqtt"
version = "0.1.5"
description = "Simple and convenient MQTT client library"
authors = [
    {name = "kimifish", email = "kimifish@proton.me"}
]
requires-python = ">=3.8"
dependencies = [
    "paho-mqtt",
]
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["kimqtt"]
